name: Bot Tweet Otomatis

on:
  schedule:
    # Menjalankan setiap 8 jam sekali.
    # '0 */8 * * *' = Pada menit ke-0, setiap 8 jam (00:00, 08:00, 16:00 UTC).
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy
      - name: Run Tweet Bot Script
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python tweet_bot.py
