name: Bot Tweet Otomatis

on:
  schedule:
    # Menjalankan setiap 90 menit.
    # Baris pertama: jalankan pada menit ke-0 setiap 3 jam (00:00, 03:00, 06:00, dst.).
    # Baris kedua: jalankan pada menit ke-30 setiap 3 jam, dimulai dari jam 1 (01:30, 04:30, 07:30, dst.).
    - cron: '0 */3 * * *'
    - cron: '30 1-23/3 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy
      - name: Run Tweet Bot Script
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python tweet_bot.py
